version: '3'
services:

  db:
    image: container-registry.oracle.com/database/enterprise:21.3.0.0 
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=Saibaba7469#  
    volumes:
      - oradata:/opt/oracle/oradata

  backend:
    image: backendsurvey:latest 
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@artemis.vsnet.gmu.edu:1521/vse18c.vsnet.gmu.edu
      - SPRING_DATASOURCE_USERNAME=s20
      - SPRING_DATASOURCE_PASSWORD=oakroort
      - SPRING_APPLICATION_JSON={"server":{"port":8080}}
    ports:
      - "8080:8080"
    depends_on:
      - db
      
  frontend:
    image: frontendsurvey:latest 
    volumes:
      - ./angular-app:/usr/share/nginx/html  
    ports:
      - "4200:4200"

volumes:
  oradata: